/*
 * eventsPriority.h
 *
 *  Created on: 17 juillet 2013
 *      Author: andre
 */

#ifndef EVENTSPRIORITY_H_
#define EVENTSPRIORITY_H_

enum event_priority_t {
	PRIORITY_EVENT_CODE_START = 1,
	PRIORITY_EVENT_SET_ID,
	PRIORITY_EVENT_GENERIC,	
	PRIORITY_EVENT_DEBUG_PAUSE_SIMULATION,	
	PRIORITY_EVENT_DEBUG_MESSAGE,	
	PRIORITY_EVENT_BLOCK_TIMER,	
	PRIORITY_BLOCKEVENT_GENERIC,
	PRIORITY_EVENT_ADD_NEIGHBOR,
	PRIORITY_EVENT_REMOVE_NEIGHBOR,
	PRIORITY_EVENT_VM_START_TRANSMISSION,	
	PRIORITY_EVENT_SEND_MESSAGE,
	PRIORITY_EVENT_NI_START_TRANSMITTING,
	PRIORITY_EVENT_NI_STOP_TRANSMITTING,
	PRIORITY_EVENT_NI_ENQUEUE_OUTGOING_MESSAGE,
	PRIORITY_EVENT_NI_RECEIVE,	
	PRIORITY_EVENT_RECEIVE_MESSAGE,
	PRIORITY_EVENT_TAP,
	PRIORITY_EVENT_SET_COLOR,
	PRIORITY_EVENT_ACCEL,
	PRIORITY_EVENT_SHAKE,
	PRIORITY_EVENT_STOP,
	PRIORITY_EVENT_VM_START_COMPUTATION,
	PRIORITY_EVENT_VM_END_COMPUTATION,
	PRIORITY_EVENT_END_SIMULATION,	
	PRIORITY_EVENT_PROCESS_LOCAL_EVENT,
};

#endif /* EVENTSPRIORITY_H_ */
